### ISSUE TITLE
Multi-lang Preview Urls aren't working

### ISSUE THREAD

**Issue by jamesvidler** [agility/gatsby-source-agilitycms#7]
When clicking preview from the CMS for a site with multi-lang enabled, the page paths don't line up and result in a 404.

For example: http://localhost:8000/home?AgilityChannelID=1&lang=en-us&agilitypreviewkey=4yVdwQ64%2bJZL8OnuT0NKZvT6b8WudEUbDq4XTXjd11Z%2bPHHf9ZQ2iGPu3TfE21bLbel7%2b4VtYUxiaLxITBeZXA%3d%3d&agilityts=20200506111046

In this case, a page has been created by gatsby with `/en/home` but not `/home`, so the preview URL breaks and nothing is loaded.

Potential fix here would be to create default preview redirects for each page (similar to what we do for dynamic pages). Or, we could create actual redirects for each page by default (without path). The problem there is what happens when you have two pages with the same name?

**Comment by jamesvidler** [comment]
It should look at the `lang` query string parameter and use that to redirect to the correct page with the language code in the prefix.

**Comment by jamesvidler** [comment]
@joshua-isaac could you take a look at this issue with our source plugin? I have some ideas of how we can fix this

**Comment by joshua-isaac** [comment]
This issue has been resolved as of version 1.6.5 of our gatsby-source-agility plugin release
